// "use client";

// import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import NavBar from "./NavBar";
import AuthProvider from "../auth/Provider";
import QueryClientProvider from "../QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Congo Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>
          <AuthProvider>
            <ChakraProvider>
              <NavBar />
              <main className="p-5">{children}</main>
            </ChakraProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
